/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.google.firebase.firebase.admin)
    api(libs.org.springframework.retry.spring.retry)
    api(libs.com.google.code.gson.gson)
    api(libs.com.stripe.stripe.java)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.io.github.long23112002.common.service)
    api(libs.com.vladmihalcea.hibernate.types.v52)
    api(libs.io.jsonwebtoken.jjwt.api)
    api(libs.io.jsonwebtoken.jjwt.impl)
    api(libs.io.jsonwebtoken.jjwt.jackson)
    api(libs.org.springframework.boot.spring.boot.starter.data.mongodb)
    api(libs.org.modelmapper.modelmapper)
    api(libs.com.corundumstudio.socketio.netty.socketio)
    api(libs.com.mailjet.mailjet.client)
    api(libs.org.springframework.boot.spring.boot.starter.data.redis)
    api(libs.com.mailgun.mailgun.java)
    api(libs.org.springframework.cloud.spring.cloud.starter.openfeign)
    api(libs.io.minio.minio)
    runtimeOnly(libs.org.postgresql.postgresql)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")
    testCompileOnly("org.projectlombok:lombok:1.18.30")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.30")
}

group = "org.example"
version = "0.0.1-SNAPSHOT"
description = "ecommerce-fashion"
java.sourceCompatibility = JavaVersion.VERSION_21
java.targetCompatibility = JavaVersion.VERSION_21


publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
