logging:
  level:
    org:
      springframework: WARN
      hibernate.SQL: DEBUG
    org.springframework.web.servlet: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: WARN


stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  signing:
    secret: ${STRIPE_SIGNING_SECRET}



jwt:
  key: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS}
refresh-token:
  expiration: ${JWT_REFRESH_EXPIRATION_MS}
  key: ${JWT_REFRESH_SECRET}

reset_token:
  expiration: ${RESET_PASSWORD_TOKEN_EXPIRATION_MS}

mailjet:
  api:
    key: ${MJ_APIKEY_PUBLIC}
    secret: ${MJ_APIKEY_PRIVATE}



#facebook:
#  client-id: ${FACEBOOK_CLIENT_ID}
#  client-secret: ${FACEBOOK_CLIENT_SECRET}
#  redirect-uri: ${FACEBOOK_REDIRECT_URI}
#
#google:
#  client-id: ${GOOGLE_CLIENT_ID}
#  client-secret: ${GOOGLE_CLIENT_SECRET}
#  redirect-uri: ${GOOGLE_REDIRECT_URI}



minio:
  endpoint: ${MINIO_ENDPOINT}
  access:
    key: ${MINIO_ACCESS_KEY}
  secret:
    key: ${MINIO_SECRET_KEY}
  bucket:
    name: ${MINIO_BUCKET_NAME}

socketio:
  host: ${SOCKETIO_HOST}
  port: ${SOCKETIO_PORT}




spring:
  main:
    banner-mode: off
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DATABASE_INDEX}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
      enabled: true



  application:
    name: ecommerce-fashion

  server:
    port: ${PORT_SERVER}

  datasource:
    url: ${POSTGRESQL_DATABASE_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: ${DB_CONNECTION_TIMEOUT:5000}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:100}
      max-lifetime: ${DB_MAX_LIFETIME:1000000}
  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
        jdbc:
          time_zone: UTC
        type:
          jsonb: com.vladmihalcea.hibernate.type.json.JsonBinaryType
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      register-types: auto
      ddl-auto: update
    open-in-view: false
    show-sql: true

  data:
    mongodb:
      uri: mongodb://${MONGO_DB_HOST}:${MONGO_DB_PORT}/${MONGO_DB_NAME}






